### ISSUE TITLE
Application Error- Heroku error upon navigating to web app

### ISSUE THREAD

**Issue by DigitalSecurityMod** [micthiesen/spotify-my-slack#19]
**Description**: The Spotify My Slack app seems to be down. I do not see any status appearing in my work space when listening to music. Upon navigating to https://spotify-my-slack.micthiesen.ca/, a Heroku Application error appears 
![image](https://user-images.githubusercontent.com/25405356/74551903-b48ae680-4f19-11ea-8051-89d83aeaf477.png)

**Steps to Reproduce**
1. Go to https://spotify-my-slack.micthiesen.ca/

**Comment by micthiesen** [comment]
Hey there. I've sadly decided to stop supporting Spotify my Slack for the foreseeable future, which is why it's not working. I may pick it up again at some point but can't make any promises.
