### ISSUE TITLE
Spotify not connecting with "Connect through facebook"

### ISSUE THREAD

**Issue by LosaMatova** [micthiesen/spotify-my-slack#8]
Hello,

I recently tried your app. Installed it, connected slack, connected a "family" spotify account through "connect with facebook" and changed my song on my Linux Spotify client.

No status updated, and the button to connect Spotify didn't change to "connected"

**Comment by LosaMatova** [comment]
Please close. 

It took 3-4 tries, and uninstalling and reinstalling the app - but I got it working!

**Comment by micthiesen** [comment]
Glad you got it working! This is actually a known issue (#9). I just haven't got around to fixing it yet.
