### ISSUE TITLE
Connecting to Spotify requires multiple attempts

### ISSUE THREAD

**Issue by micthiesen** [micthiesen/spotify-my-slack#9]
Not sure what's happening here, but sometimes you have to click "Connect Spotify" multiple times before it registers. This is a more general issue to replace #3 which made a few too many assumptions.

**Comment by micthiesen** [comment]
Figured it out. Spotify is throttling the authentication requests (hard to believe this, I thought it was just the player state requests). This is why it eventually works. The times it doesn't work, at 429 status code is returned.

I'll have to think of the best way to handle this... Retry while holding the client's request, or present an error message?

**Comment by Moulick** [comment]
Asking people to press retry will also just amplify the api request and throttling

**Comment by micthiesen** [comment]
Yeah. Do you have a better solution?

**Comment by p-glynn** [comment]
could maybe have the click display some feedback and set an interval which tries until it succeeds. i'll have a look later

**Comment by jeanlucaslima** [comment]
Just noticed this issue. 

Spotify documentation says: 

Note: If Web API returns *status code 429*, it means that you have sent too many requests. When this happens, check the `Retry-After` header, where you will see a number displayed. This is the number of _seconds that you need to wait,_ before you try your request again.

**Comment by jeanlucaslima** [comment]
Maybe one option is to least help the user setting up automatically this waiting time.

**Comment by micthiesen** [comment]
Yeah I think an automated retry mechanism is the best solution for now. I'll have to think about how to work it into the authentication flow.

I probably won't get to this right away, though.

**Comment by jeanlucaslima** [comment]
@micthiesen if you point out what to change, I can try creating a PR this week.

**Comment by micthiesen** [comment]
That would be great if you want to give it a go. I _think_ this is where you can check for a 429 status code and retry: https://github.com/micthiesen/spotify-my-slack/blob/master/src/views/spotify-grant-callback.js#L15

I'd recommend failing after a predetermined number of retries (maybe 10) to prevent a possible infinite loop. Note that I've got some linting in CI (eslint).

One reason I've been putting this off is because I want to refactor the Spotify integration to not rely on the `spotify-web-api-node` third party library. But that can wait.

**Comment by jeanlucaslima** [comment]
Great stuff, can't do much today but I'll be looking into this during the week, thanks!

**Comment by rtsio** [comment]
Now it won't connect at all, even after clicking ~20 times with waits in-between :-(

Edit: never mind, took about 50+ tries and then it worked :-)

**Comment by frugoman** [comment]
I guess you can retry automatically a few times when spotify returns that code

**Comment by joannawheeler** [comment]
connected once
then never again
ugh

**Comment by joannawheeler** [comment]
YES! I hyper clicked it probably 50 times super fast and finally it connected. Going slow wasnt working at all. or double clicking. just click a fuckton of times over and over. my slack was NOT connected yet btw.
good luck ya'll this is a sick app.

**Comment by micthiesen** [comment]
This issue relates to an old version of SmS which is no longer in use.
